### ISSUE TITLE
Slightly strange names

### ISSUE THREAD

**Issue by eschnett** [omlins/JUHPC#17]
To use JUHPC I need to set it up first. That step uses a script called `juhpc`.

Later, when I want to use JUHPC to start Julia, then I have to activate it, and you suggest the name `juhpc_setup` for this.

Isn't that reversed? Shouldn't the first step be called `juhpc_setup` (or `juhpc_install`), and later, when I'm using juhpc, shouldn't that live in a directory called `juhpc`?

**Comment by omlins** [comment]
Your comments in the other issue have shown that it has not been completely clear to you what JUHPC does. Please look at my replies and tell me if you still think that something could be improved in that direction

**Comment by omlins** [comment]
@eschnett any more comments on this? If so please check against the documentation which should make clear why things are called the way they're called.

**Comment by omlins** [comment]
I believe it is important to pay attention to the difference between (to) "set up" (verb) and (a) "setup" (noun). Considering this, the names were chosen given the following logic:
- the project and the script are called *juhpc*
- using juhpc we can install multiple *HPC setups* (however, **we do not install** *juhpc*, we only download and use it)
- to use a HPC setup, we activate it
